server:
  port: 8080

database:
  host: mysql       # <--- 必须是 "mysql"，不能是 127.0.0.1
  port: 3306
  user: root
  password: password
  dbname: sentinel

rabbitmq:
  host: rabbitmq    # <--- 必须是 "rabbitmq"，不能是 127.0.0.1
  port: 5672
  user: guest
  password: guest
  queue_name: scan_tasks