services:
  mysql:
    image: mysql:8.0
    container_name: cloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_compute
    ports:
      - "3306:3306"
    restart: always


  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloud-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  sentinel:
    build: .
    container_name: cloud-sentinel
    command: ./server
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_HOST=mysql
      - MQ_HOST=rabbitmq 
      - MYSQL_DATABASE=cloud_compute 
    depends_on:
      - mysql
      - rabbitmq         
    restart: always

  agent:
    build: .
    container_name: cloud-agent-01
    command: ./agent
    environment:
      - SERVER_ADDR=sentinel:9090
    depends_on:
      - sentinel
    restart: always