
services:
  mysql:
    image: mysql:8.0
    container_name: cloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_compute
    ports:
      - "3306:3306"
    restart: always

  server:
    build: .
    container_name: cloud-server
    command: ./server
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    restart: always

  agent:
    build: .
    container_name: cloud-agent-01
    command: ./agent
    environment:
      - SERVER_ADDR=server:9090
    depends_on:
      - server
    restart: always